name: Create Branch from Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to base new branch on"
        required: true
      branch_name:
        description: "New branch name"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.commit_sha }}
      - name: Set up git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Create and push new branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git switch -c "${{ github.event.inputs.branch_name }}"
          git push origin "${{ github.event.inputs.branch_name }}"
